import pytest

from app.customer_agent import CUSTOMER_QUESTION_PROMPT, CUSTOMER_RESOLUTION_PROMPT, CUSTOMER_SIDE_DATA_DECISION_PROMPT, CUSTOMER_SYSTEM_PROMPT, CUSTOMER_VERIFICATION_PROMPT
from app.handoff import SUPPORT_HANDOFF_SYSTEM_PROMPT
from app.support_agent import SUPPORT_INVESTIGATION_SYSTEM_PROMPT


@pytest.mark.parametrize("prompt", [CUSTOMER_SYSTEM_PROMPT, CUSTOMER_QUESTION_PROMPT, CUSTOMER_SIDE_DATA_DECISION_PROMPT, CUSTOMER_RESOLUTION_PROMPT, CUSTOMER_VERIFICATION_PROMPT, SUPPORT_HANDOFF_SYSTEM_PROMPT, SUPPORT_INVESTIGATION_SYSTEM_PROMPT])
def test_model_prompts_require_simplified_chinese(prompt: str) -> None:
    assert "简体中文" in prompt
